### ISSUE TITLE
Some basic questions

### ISSUE THREAD

**Issue by vinhqdang** [discoverychallenge/dc-evaluator-2016#2]
Dear Sir / Madam

1. Do I have to participate on both tasks?

2. What kind of programming languages / libraries I could use? Do I have to use Python, or I can choose other language?

Thank you very much

**Comment by discoverychallenge** [comment]
Hi,
1 you can participate in any of the tasks individually
2 you can choose any programming languages and tools
3 Check out the rules section:
  In order to be eligible for the prize, you have to make your method reproducible to the greatest possible extent, including:
  + The team has to submit a publication and present the results at the conference.
  + Release the source code whenever possible, e.g. on GitHub. In other words, we encourage teams for reproducibility.
